# The URL the site will be built for
base_url = "https://mataiodoxion.github.io"

title = "Mataiodoxion"

theme = "terminus"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate feed
generate_feeds = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
theme = "catppuccin-mocha"

[extra]
main_menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

socials = [
    { name = "email", url = "mailto:mataiodoxion@protonmail.com" },
]
